### ISSUE TITLE
catkin build fail

### ISSUE THREAD

**Issue by Cianciu** [ethz-asl/suitesparse#26]
The package did't build on machine with Ubuntu 16.04, ROS Kinetic.
The problem was due to a non existing installation path.

To solve the issue, install commands at the end of the CMakeLists.txt file have been removed.

**Comment by HannesSommer** [comment]
Thanks for reporting! I believe these lines https://github.com/ethz-asl/suitesparse/blob/master/CMakeLists.txt#L62-L70 are wrong and installation was just never tested :). The failure is in the directories to be installed (second argument of install(), such as `include`). They don't exist in the source folder and therefore cannot be installed.

That leaves two questions:
1. Why did an installation attempt happen in your case: Could it be that you used the `--install` option with your `catkin config` invocation? If so, why? And if you don't actually need it just undo it with `catkin config --no-install` or you will probably run in other broken install parts that just never got tested :). (@mbuerki  you were telling me about deployment plans once: does that mean we need cake install time support for all involved packages?)

2. What to do with these lines: I'd suggest to remove them and don't support installation until somebody actually needs it.

**Comment by mbuerki** [comment]
@HannesSommer yeah, fancy deployment plans are on hold for now ;-) I'm pretty sure we'll just do it the simple-slightly-ugly-way :-( I'm in general still somewhat interested in setting up a real deployment pipeline, but I doubt it's worth the tremendous effort necessary for anyone right now.

**Comment by Cianciu** [comment]
I found out that for some reason in the Catkin config I had

Install Space Layout:        merged

When it is set to none, it builds.

**Comment by HannesSommer** [comment]
This was addressed with #27.
