### ISSUE TITLE
Linking broken with aslam_optimizer

### ISSUE THREAD

**Issue by smauq** [ethz-asl/suitesparse#29]
@eggerk The new changes broke how the suitesparse package links stuff, which in turn causes aslam_optimizer packages to not compile because of missing headers/libraries.

**Environment:**
Ubuntu 14.04 with Indigo / Ubuntu 16.04 with Kinetic
Clean catkin workspace, with merged devel space and only extending /opt/ros/\<ROS-VERSION\>

**Steps to reproduce:**
catkin build sparse_block_matrix
(similar error also for the other packages in the aslam_optimizer)

**Issue:**
Build fails with error
`sparse_helper.h:27:21: fatal error: cholmod.h: No such file or directory`

Which is a header file in SuiteParse, the linking of which should be handled by this package. If manually added to CPATH, compilation will fail with missing references to functions during linking.

**Comment by HannesSommer** [comment]
I can confirm problem and solution. This is the fixing PR #30.

**Comment by HannesSommer** [comment]
Sorry, for my optimistic (automatic) closing. In fact this isn't done, yet. Hopefully PR #31 is doing the trick.

**Comment by HannesSommer** [comment]
Finally, PR #32  seems to have solved this issue.
